name: Build ZIP

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies using composer
      uses: php-actions/composer@v6
      with:
        php_version: 7.1
    - name: Prepare folder structure
      run: >-
        shopt -s extglob
        mkdir xqmaileon
        mv !(xqmaileon) xqmaileon
    - name: Create ZIP archive
      run: zip -r xqmaileon xqmaileon -x "*.git*" "*DOCKER_ENV" "*docker_tag" "*output.log"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: xqmaileon.zip
